### ISSUE TITLE
Add React Router, NavBar and Footer component

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/good-first-issues#20]
## Description 

- [X] Add React Router
- [X] Add NavBar component
- [X] Add Footer components

**Comment by HarshCasper** [comment]
Fixed here: https://github.com/HarshCasper/good-first-issues/commit/f038c0b22aa4cd0015045e96defe449282aaa0e1

**Comment by RiyaGupta999** [comment]
Thanks
