### ISSUE TITLE
Add React Routing, UI Component Libraries and other stuff

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/good-first-issues#7]
## Description

As the React App has been initialized, we can work on the next few things now to set up the development process with React: 

- Add React Routing
- Add React Bootstrap UI Library
- Add a NavBar and Footer (Dummy Content)

**Comment by Ayushmina-20** [comment]
Can you elaborate for which pages you required routing??
I want to contribute

**Comment by HarshCasper** [comment]
Hi @Ayushmina-20 

This has already been worked on and merged.

**Comment by Ayushmina-20** [comment]
Ok, thanks For letting me know and sorry from my side
